---
title: "KW looking at patterns of prevalence using all variables"
date: 2018-12-20
output: 
  html_notebook:
    toc: true
    toc_float: true
---

```{r}
temp <- df_all_resp %>%
  select(taves_ctry, question_text, ends_with("mean")) %>%
  mutate(abs_val_mean = abs(val_mean)) %>%
  gather(index, score, ends_with("mean")) %>%
  arrange(taves_ctry, question_text, index) %>%
  mutate(site_index = paste(taves_ctry, index, sep = "_")) %>%
  select(question_text, site_index, score) %>%
  spread(question_text, score) %>%
  column_to_rownames("site_index")
```

```{r}
hclust_all <- temp %>%
  t() %>%
  dist() %>%
  hclust()
```

```{r, fig.width = 8, fig.asp = 1}
hclust_all %>% 
  as.dendrogram() %>% 
  set("labels_col", k = 9, value = c("#a6cee3", "#1f78b4", "#b2df8a",
                                     "#33a02c", "#fb9a99", "#e31a1c", 
                                     "#fdbf6f", "#ff7f00", "#cab2d6")) %>% 
  plot(horiz = T, xlim = c(3, -10), axes = F)
```

```{r}
temp_df <- data.frame(cluster = cutree(hclust_all, 9)) %>%
  rownames_to_column("question_text") %>%
  mutate(level1 = case_when(cluster %in% c(1, 3, 8, 9, 5) ~ "13895",
                            cluster %in% c(4, 6, 2, 7) ~ "4627"),
         level2a = case_when(cluster %in% c(1, 3) ~ "13",
                             cluster %in% c(8, 9, 5) ~ "895"),
         level2b = case_when(cluster %in% c(4, 6, 2) ~ "462",
                             cluster %in% c(7) ~ "7"),
         level2 = case_when(cluster %in% c(1, 3) ~ "13",
                            cluster %in% c(8, 9, 5) ~ "895",
                            cluster %in% c(4, 6, 2) ~ "462",
                            cluster %in% c(7) ~ "7"),
         level1 = factor(level1, levels = c("13895", "4627")),
         level2a = factor(level2a, levels = c("13", "895")),
         level2b = factor(level2b, levels = c("462", "7")),
         level2 = factor(level2, levels = c("13", "895", "462", "7"))) %>%
  full_join(df_all_resp %>% 
              rename(prev_cluster = cluster,
                     prev_level1 = level1,
                     prev_level2 = level2,
                     prev_level2uncommon = level2uncommon,
                     prev_level2common = level2common,
                     prev_level3 = level3) %>%
              mutate(abs_val_mean = abs(val_mean)))
```

```{r}
temp_df %>%
  count(cluster, prev_cluster)
```

```{r, fig.width = 6, fig.asp = 0.8}
temp_df %>%
  ggplot(aes(x = question, y = prev_mean, color = taves_ctry, label = prev_n)) +
  facet_grid(cols = vars(level1, level2, cluster), 
             rows = vars(taves_ctry), 
             scales = "free_x", space = "free_x") +
  geom_hline(yintercept = 0.5, lty = 2) +
  geom_pointrange(aes(ymin = prev_ci_lower, ymax = prev_ci_upper)) +
  geom_text(size = 2, y = 0.05, color = "black") +
  scale_color_brewer(palette = "Set2") +
  ylim(0, 1) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none") +
  labs(title = "Clustering with all variables PREVALENCE: Proportion of participants who endorsed experience",
       subtitle = "By site (rows), question (x-axis), and levels 1-2 grouping of clusters (columns)\nNumbers for each question indicate the total number of participants from that site who responded to that question; error bars are 95% bootstrapped CIs",
       x = "Question",
       y = "Prevalence (0-1)", color = "Site")
```

<P style="page-break-before: always">
```{r, fig.width = 6, fig.asp = 0.8}
temp_df %>%
  ggplot(aes(x = question, y = app_mean, color = taves_ctry, label = app_n)) +
  facet_grid(cols = vars(level1, level2, cluster), 
             rows = vars(taves_ctry), 
             scales = "free_x", space = "free_x") +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = app_ci_lower, ymax = app_ci_upper)) +
  geom_text(size = 2, y = -0.95, color = "black") +
  scale_color_brewer(palette = "Set2") +
  ylim(-1, 1) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none") +
  labs(title = "Clustering with all variables APPRAISAL: Mean response to whether the participant appraised experience as religious/spiritual",
       subtitle = "By site (rows), question (x-axis), and levels 1-2 grouping of clusters (columns)\nNumbers for each question indicate the total number of participants from that site who responded to that question; error bars are 95% bootstrapped CIs",
       x = "Question",
       y = "Appraisal (-1: no, 0: unsure, +1: yes)", color = "Site")
```

<P style="page-break-before: always">
```{r, fig.width = 6, fig.asp = 0.8}
temp_df %>%
  ggplot(aes(x = question, y = val_mean, color = taves_ctry, label = val_n)) +
  facet_grid(cols = vars(level1, level2, cluster), 
             rows = vars(taves_ctry), 
             scales = "free_x", space = "free_x") +
  geom_hline(yintercept = 0, lty = 2) +
  geom_pointrange(aes(ymin = val_ci_lower, ymax = val_ci_upper)) +
  geom_text(size = 2, y = -0.95, color = "black") +
  scale_color_brewer(palette = "Set2") +
  ylim(-1, 1) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none") +
  labs(title = "Clustering with all variables VALENCE: Mean response to whether experience was considered positive/negative",
       subtitle = "By site (rows), question (x-axis), and levels 1-2 grouping of clusters (columns)\nNumbers for each question indicate the total number of participants from that site who responded to that question; error bars are 95% bootstrapped CIs",
       x = "Question",
       y = "Valence (-1: negative, 0: neutral, +1: positive)", color = "Site")
```

```{r, fig.width = 6, fig.asp = 0.8}
temp_df %>%
  ggplot(aes(x = question, y = abs_val_mean, color = taves_ctry, label = val_n)) +
  facet_grid(cols = vars(level1, level2, cluster), 
             rows = vars(taves_ctry), 
             scales = "free_x", space = "free_x") +
  geom_hline(yintercept = 0.5, lty = 2) +
  geom_point() +
  # geom_pointrange(aes(ymin = val_ci_lower, ymax = val_ci_upper)) +
  geom_text(size = 2, y = 0.05, color = "black") +
  scale_color_brewer(palette = "Set2") +
  ylim(0, 1) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none") +
  labs(title = "Clustering with all variables ABSOLUTE VALENCE: Mean absolute response to whether experience was considered positive/negative",
       subtitle = "By site (rows), question (x-axis), and levels 1-2 grouping of clusters (columns)\nNumbers for each question indicate the total number of participants from that site who responded to that question; error bars are 95% bootstrapped CIs",
       x = "Question",
       y = "Valence (0: neutral, 1: negative/positive)", color = "Site")
```

<P style="page-break-before: always">
```{r, fig.width = 6, fig.asp = 0.8}
temp_df %>%
  ggplot(aes(x = question, y = sig_mean, color = taves_ctry, label = sig_n)) +
  facet_grid(cols = vars(level1, level2, cluster), 
             rows = vars(taves_ctry), 
             scales = "free_x", space = "free_x") +
  geom_hline(yintercept = 0.5, lty = 2) +
  geom_pointrange(aes(ymin = sig_ci_lower, ymax = sig_ci_upper)) +
  geom_text(size = 2, y = 0.05, color = "black") +
  scale_color_brewer(palette = "Set2") +
  ylim(0, 1) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none") +
  labs(title = "Clustering with all variables SIGNIFICANCE: Mean response to how significant experience was considered",
       subtitle = "By site (rows), question (x-axis), and levels 1-2 grouping of clusters (columns)\nNumbers for each question indicate the total number of participants from that site who responded to that question; error bars are 95% bootstrapped CIs",
       x = "Question",
       y = "Significance (0: not, 0.5: somewhat, 1: very)", color = "Site")
```


